name: WebdriverIO Boilerplate

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: "BrowserStack Env Setup"
        uses: "browserstack/github-actions/setup-env@master"
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: BUILD_INFO
          project-name: "REPO_NAME"
      - name: Run test
        id: test
        continue-on-error: true
        run: npm run test-prod-bstack
      - run: npm run generateMochawesome
      - name: Archive mochawesome reports
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: mochawesome-report/
      # - name: Check if tests have failed
      #   if: steps.test.outcome == 'failure'
      #   run: exit 1
